### PR TITLE
added exp to jwt and saved to redis

### PR DESCRIPTION
**Pull request by mosajjal**

### CODE REVIEW

**Comment by LionZXY** [comment]
@mosajjal Опасный парень

**Comment by LionZXY** [comment]
@mosajjal Оно после этого точно работать будет?

**Comment by mavahedinia** [comment]
@LionZXY would you speak english so that we can understand too? :|

according to gtranslate you are asking whether is it working or not, and the answer is it is under development and not completely even close to release!

**Comment by LionZXY** [comment]
... sorry.
You project or account has connect to GitHub telegram bot? 
I don't write anything here.

**Comment by mavahedinia** [comment]
yes it is connected to Github bot, but this is screenshot from github :(
image

**Comment by LionZXY** [comment]
Maybe is a bug in GitHub bot. I reply this on other issue.

**Pull request merged**
